
  begin
    
  rescue Exception => e
    puts "caught exception #{e}! ohnoes!"
  end
